### ISSUE TITLE
2.1.1 missing from previous release page.

### ISSUE THREAD

**Issue by braymp** [CellProfiler/cellprofiler.github.com#68] opened 2016-10-14 19:17 UTC
http://cellprofiler.org/previous_releases/ has the link to the last release as 2.1.0, rather than 2.1.1. Interestingly, http://cellprofiler.org/download/ takes you to a 2.1.1 download page.

**Comment by mcquin** [comment] 2016-10-17 13:25
Duplicate of #54

**Closed by mcquin** 2016-10-17 13:25 UTC
Labels: bug
