### ISSUE TITLE
Add file create date to "Nightly" builds

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com#117] opened 2017-01-09 20:57 UTC
Both CP and CPA Windows "nightly" builds are 6+ months old (CP issue here https://github.com/CellProfiler/CellProfiler/issues/2552).  I suggest that the releases page actively grab the date of the nightly build's creation date and post this on the releases page.  Otherwise there is no way for a user to know whether this is truly a nighty build.

**Comment by dlogan** [comment] 2017-01-09 20:58
See also https://github.com/CellProfiler/cellprofiler.github.com/issues/12

**Comment by AnneCarpenter** [comment] 2017-01-10 14:32
duplicate of #111 - we definitely want this fixed!

**Closed by AnneCarpenter** 2017-01-10 14:32 UTC
