### ISSUE TITLE
Improve mobile friendliness 

### ISSUE THREAD

**Issue by N3llz** [CellProfiler/cellprofiler.github.com#116] opened 2017-01-09 19:41 UTC
Currently, on mobile phones, there is no menu visible, so people can only have the option to click "download" and that is it. This makes the website useless on a mobile phone.

**Comment by AnneCarpenter** [comment] 2017-01-10 14:31
Duplicate of #17, Claire seems to have Id'd a relevant fix.

**Closed by AnneCarpenter** 2017-01-10 14:31 UTC
