### ISSUE TITLE
Published pipelines page 404's 

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/cellprofiler.github.com#28] opened 2016-10-03 13:30 UTC
Hat tip to [the forum](http://forum.cellprofiler.org/t/temporary-location-for-previous-builds/4001/4?u=bcimini).    Bad link is [here](http://cellprofiler.org/examples/published_pipelines.html)

**Comment by dlogan** [comment] 2016-10-04 17:26
Other broken links, including that one above:

- [ ] http://cellprofiler.org/examples/published_pipelines.html
- [ ] http://cellprofiler.org/tracer.  When fixed, please close this issue too: https://github.com/CellProfiler/cellprofiler.github.com-backup/issues/5#issuecomment-251448418
- [ ] Googling "CellProfiler interfaces" returns this (http://cellprofiler.org/interfaces.shtml) which returns a 404.  It should be simply http://cellprofiler.org/interfaces/

**Comment by dlogan** [comment] 2016-10-04 18:38
Duplicate of https://github.com/CellProfiler/cellprofiler.github.com/issues/31 in the list above

**Closed** 2016-10-04 21:09 UTC
